### ISSUE TITLE
how can we give initial values

### ISSUE THREAD

**Issue by HPsunilkumar** [gogoair/react-combo-select#15]
thanks for your efforts, and  i need to select some values in initial time of rendering how can i give that values? value={standardArray[2]} is not working

**Comment by markokostovski** [comment]
This is kinda bare minimum for your setup. You need to have both data and value, but value has to be inside of data.

`const standardArray = ["JA007D", "JA008D", "JA009D", "JA010D"];
<ComboSelect data={standardArray} value={standardArray[2]}/>`

I can think that you can have problem if you use `map`. Anyway, copy little more code here, so that we can be more helpful :D

**Comment by HPsunilkumar** [comment]
Thank you markokostovski for your kind help

**Comment by markokostovski** [comment]
You're welcome :D
